#!/usr/bin/env bash

if [[ $DEBUG == 'true' ]]; then
  set -euxo pipefail
else
  set -euo pipefail
fi
IFS=$'\n\t'

kill_polybar() {
  pkill polybar || true
  # Wait until the processes have been shut down
  while pgrep -x polybar >/dev/null; do sleep 1; done
}

move_ws() {
  WORKSPACE=$1
  DIRECTION=$2
  i3-msg workspace "$WORKSPACE"
  i3-msg move workspace to output "$DIRECTION"
}

set_wallpaper() {
  SCREEN=$1
  MODE=$2
  IMAGE=$3
  nitrogen --head="$SCREEN" --set-"$MODE" --save ~/pictures/wallpapers/"$IMAGE"
}

start_bar() {
  MONITOR=$1
  BAR=$2
  polybar --reload "$BAR" </dev/null >"/var/tmp/polybar-$MONITOR.log" 2>&1 &
}

work() {
  xrandr \
    --output eDP-1 --mode 1920x1080 --pos 5280x824 --rotate normal \
    --output DP-1 --off \
    --output HDMI-1 --off \
    --output DP-2 --mode 3840x2160 --pos 1440x284 --rotate normal \
    --output DP-1-1 --off \
    --output DP-1-2 --mode 2560x1440 --pos 0x0 --rotate right \
    --output DP-1-3 --off \
    --output DP-2-1 --off \
    --output DP-2-2 --off \
    --output DP-2-3 --off
  set_wallpaper 2 scaled IMG_20190901_161515-PANO.jpg
  set_wallpaper 1 auto IMG_20190903_163002-EFFECTS.jpg
  set_wallpaper 0 zoom-fill IMG_20190730_155936-PANO.jpg
  move_ws 2 left
  TRAY_POSITION=right start_bar DP-2 4k
  start_bar eDP-1 1080p
}

laptop() {
  xrandr --auto
  set_wallparer 0 auto EFFECTS.jpg
  TRAY_POSITION=right start_bar eDP-1 1080p
}

cmd_args() {
  if [[ $# -ne 1 ]]; then
    laptop
    exit 0
  fi
  for i in "$@"; do
    case $i in
    -w | --work) work ;;
    *) laptop ;;
    esac
  done
}

(
  flock 200
  [ -f ~/.dotfiles/Xresources ] && xrdb -merge -I"$HOME" ~/.dotfiles/Xresources
  kill_polybar
  cmd_args "$@"
) 200>/var/tmp/polybar-launch.lock
