#!/usr/bin/env bash

set -eo pipefail

kill_polybar() {
	pkill polybar
	# Wait until the processes have been shut down
	while pgrep -x polybar >/dev/null; do sleep 1; done
}

dual_screen() {
	xrandr --output eDP-1 --auto --right-of DP-2 --output DP-2 --mode 3840x2160 --primary
	polybar -q i3 &
	polybar -q second &
	i3-msg workspace 2
	i3-msg move workspace to output left
}

single_screen() {
	xrandr --auto
	polybar -q i3 &
}

[ -f ~/.dotfiles/Xresources ] && xrdb -merge -I"$HOME" ~/.dotfiles/Xresources
kill_polybar
case "$1" in
1) single_screen ;;
2) dual_screen ;;
"--bar")
	case "$2" in
	2)
		echo -n "dual bar "
		polybar -q second &
		polybar -q i3 &
		echo "done"
		;;
	*) polybar -q i3 &;;
	esac
	;;
*) single_screen ;;
esac
feh --bg-fill "$HOME"/pictures/wallpaper.jpg
